=== SysFera/GoDIET/GoDIET.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT diet_configuration (goDiet?,resources,diet_services,diet_hierarchy)>

<!--- Define behavior of GoDIET -->
<!ELEMENT goDiet EMPTY>
<!ATTLIST goDiet
    debug CDATA #IMPLIED
    saveStdOut CDATA #IMPLIED
    saveStdErr CDATA #IMPLIED
    useUniqueDirs CDATA #IMPLIED
    log CDATA #IMPLIED
  >

<!--- Define resources available for data storage and compution -->
<!--- Must define local scratch directory for use before launch -->
<!ELEMENT resources (scratch,storage+,compute*,cluster*)>

<!ELEMENT storage (scratch,scp)>
<!ATTLIST storage
    label CDATA #REQUIRED
  >
<!ELEMENT scratch EMPTY>
<!ATTLIST scratch 
    dir CDATA #REQUIRED
  > 
<!ELEMENT scp EMPTY>
<!ATTLIST scp
    login CDATA #IMPLIED
    server CDATA #REQUIRED
  >

<!ELEMENT compute (ssh,env?,end_point?)>
<!ATTLIST compute
    disk CDATA #REQUIRED
    label CDATA #REQUIRED
    login CDATA #IMPLIED
  >
<!ELEMENT cluster (env,node+)>
<!ATTLIST cluster
    disk CDATA #REQUIRED
    label CDATA #REQUIRED
    login CDATA #IMPLIED
  >
<!ELEMENT node (ssh,end_point?)>
<!ATTLIST node
    label CDATA #REQUIRED
  >
<!ELEMENT ssh EMPTY>
<!ATTLIST ssh    
    server CDATA #REQUIRED
    login CDATA #IMPLIED
  >
<!ELEMENT env (var*)>
<!ELEMENT end_point EMPTY>
<!ATTLIST end_point
    contact CDATA #IMPLIED
    startPort CDATA #IMPLIED
    endPort CDATA #IMPLIED
  >
<!ELEMENT var EMPTY>
<!ATTLIST var
   name CDATA #REQUIRED
   value CDATA #REQUIRED
  >
<!--- Define other DIET services to run alongside hierarchy -->
<!ELEMENT diet_services (omni_names,log_central?,log_tool?,diet_statistics?)>
<!ELEMENT omni_names (config,cfg_options?)>
<!ATTLIST omni_names
    contact CDATA #REQUIRED
    port CDATA #IMPLIED    
  >
<!ELEMENT log_central (config)>
<!ATTLIST log_central
    connectDuringLaunch CDATA #IMPLIED
  >
<!ELEMENT log_tool (config)>
<!ELEMENT diet_statistics EMPTY>

<!--- Define hierarchy of agents and SeDs -->
<!ELEMENT diet_hierarchy (master_agent+)>

<!ELEMENT master_agent (config,cfg_options?,ma_dag*,local_agent*,SeD*)>
<!ATTLIST master_agent
    label CDATA #IMPLIED
    useDietStats CDATA #IMPLIED
  >
<!ELEMENT ma_dag (config,cfg_options?,parameters?)>
<!ATTLIST ma_dag 
    label CDATA #IMPLIED
    useDietStats CDATA #IMPLIED        
>
  
<!ELEMENT local_agent (config,cfg_options?,local_agent*,SeD*)>
<!ATTLIST local_agent
    label CDATA #IMPLIED
    useDietStats CDATA #IMPLIED    
  >

<!ELEMENT SeD (config,cfg_options?,parameters?)>
<!ATTLIST SeD 
    label CDATA #IMPLIED
    useDietStats CDATA #IMPLIED    
  >

<!--- Configuration for agents and seds -->
<!ELEMENT config EMPTY>
<!ATTLIST config
    remote_binary CDATA #REQUIRED    
    server CDATA #REQUIRED
  >
<!ELEMENT parameters EMPTY>
<!ATTLIST parameters 
    string CDATA #REQUIRED
  >  
  <!--- Cfg options for agents, seds and also omniNames -->
  <!ELEMENT cfg_options (option+)>
 <!ELEMENT option EMPTY>
 <!ATTLIST option
   name CDATA #REQUIRED
   value CDATA #REQUIRED
  >

=== SysFera/GoDIET/examples/example1.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE diet_configuration SYSTEM "../GoDIET.dtd">

<diet_configuration>
  <goDiet debug="1"/>

  <resources>
    <scratch dir="/home/hdail/tmp/diet_scratch1"/>
    
    <storage label="localDisk">
        <scratch dir="/home/hdail/tmp/diet_scratchLocal"/>
        <scp server="localhost" login="hdail"/>
    </storage>
    <storage label="graalDisk">
        <scratch dir="/home/hdail/tmp/diet_scratchGraal"/>
        <scp server="graal.ens-lyon.fr" login="hdail"/>
    </storage>
     
    <compute label="localHost" disk="localDisk">
        <ssh server="localhost" login="hdail"/>
        <env path="/home/hdail/local/LogCentral/bin:/home/hdail/local/LogCentral/examples:/home/hdail/diet/omniORB-4.0.3/bin:/home/hdail/local/src/diet/install/bin:/home/hdail/local/src/diet/src/examples/dmat_manips/"
             LD_LIBRARY_PATH="/home/hdail/local/src/diet/install/lib:/home/hdail/diet/omniORB-4.0.3/lib"/>
    </compute>
    <compute label="graalHost" disk="graalDisk">
        <ssh server="graal.ens-lyon.fr" login="hdail"/>
        <env path="/home/hdail/local/LogCentral/bin:/home/hdail/local/LogCentral/examples:/home/hdail/local/src/diet/install/bin:/home/hdail/local/src/diet/src/examples/dmat_manips/:/home/hdail/local/src/diet/src/examples/scalars/"
             LD_LIBRARY_PATH="/usr/lib:/home/hdail/local/src/diet/install/lib"/>
    </compute>
  </resources>
  
  <diet_services>
    <omni_names port="2810">
        <config server="graalHost" 
                trace_level="1" 
                remote_binary="omniNames"/>
    </omni_names>
  </diet_services>
  
  <diet_hierarchy>
    <master_agent label="MyMA">
        <config server="graalHost"
                trace_level="1"
                remote_binary="dietAgent"/>
    
        <local_agent label="MyLA">
            <config server="graalHost"
                    trace_level="1"
                    remote_binary="dietAgent"/>
            
            <SeD label="MySeD">
                <config server="graalHost"
                        remote_binary="server_dmat"/>
                <parameters string="T"/>
            </SeD>
        </local_agent>
        <SeD label="MySeD">
            <config server="graalHost"
                    remote_binary="server_dmat"/>
             <parameters string="MatPROD"/>
        </SeD>
        <SeD label="MySeD">
            <config server="graalHost"
                    remote_binary="server_scalar"/>
        </SeD>
    </master_agent>
  </diet_hierarchy>      

</diet_configuration>

=== SysFera/GoDIET/examples/example2.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE diet_configuration SYSTEM "GoDIET.dtd">

<diet_configuration>
  <goDiet debug="2"
          saveStdOut="yes"
          saveStdErr="yes"
          useUniqueDirs="yes"/>

  <resources>
    <!-- local scratch space for GoDIET on machine local to GoDIET -->
    <scratch dir="/home/dail/tmp/scratch_godiet"/>

    <!-- Remote storage for launch-time -->
    <storage label="lsDisk">
        <scratch dir="/home/dail/tmp/scratch_ls"/>
        <scp server="ls2.ens.vthd.prd.fr" login="dail"/>
    </storage>
    
    <storage label="cristalDisk">
        <scratch dir="/home/hdail/tmp/scratch_godiet"/>
        <scp server="192.5.59.198" login="hdail"/>
    </storage>

    <!-- Compute hosts -->
    <compute label="ls1" disk="lsDisk">
        <ssh server="ls1.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.223"/>
    </compute>
    <compute label="ls2" disk="lsDisk">
        <ssh server="ls2.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.224"/>
    </compute>
    <compute label="ls3" disk="lsDisk">
        <ssh server="ls3.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.225"/>
    </compute>
    <compute label="ls4" disk="lsDisk">
        <ssh server="ls4.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.226"/>
    </compute>
    <compute label="ls5" disk="lsDisk">
        <ssh server="ls5.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.227"/>
    </compute>
    <compute label="ls6" disk="lsDisk">
        <ssh server="ls6.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.228"/>
    </compute>
    <compute label="ls7" disk="lsDisk">
        <ssh server="ls7.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.229"/>
    </compute>
    <compute label="ls8" disk="lsDisk">
        <ssh server="ls8.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.230"/>
    </compute>
    <compute label="ls9" disk="lsDisk">
        <ssh server="ls9.ens.vthd.prd.fr" login="dail"/>
        <env path="/home/dail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/dail/bSeries_exp/diet/install/lib:/home/dail/local/omniORB-4.0.3-gcc3/lib"/>
        <end_point contact="193.253.175.231"/>
    </compute>
    <!-- compute hosts on cristal -->
    <compute label="clus-103" disk="cristalDisk">
        <ssh server="192.5.59.198" login="hdail"/>
        <env path="/home/hdail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/hdail/bSeries_exp/diet/install/lib:/home/hdail/local/omniORB-4.0.3-gcc3/lib:/home/hdail/local/gcc-3.0.4/lib"/>
        <end_point contact="192.5.59.198"/>
    </compute>
    <compute label="clus-104" disk="cristalDisk">
        <ssh server="192.5.59.199" login="hdail"/>
        <env path="/home/hdail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/hdail/bSeries_exp/diet/install/lib:/home/hdail/local/omniORB-4.0.3-gcc3/lib:/home/hdail/local/gcc-3.0.4/lib"/>
        <end_point contact="192.5.59.199"/>
    </compute>
    <compute label="clus-105" disk="cristalDisk">
        <ssh server="192.5.59.200" login="hdail"/>
        <env path="/home/hdail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/hdail/bSeries_exp/diet/install/lib:/home/hdail/local/omniORB-4.0.3-gcc3/lib:/home/hdail/local/gcc-3.0.4/lib"/>
        <end_point contact="192.5.59.200"/>
    </compute>
    <compute label="clus-106" disk="cristalDisk">
        <ssh server="192.5.59.201" login="hdail"/>
        <env path="/home/hdail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/hdail/bSeries_exp/diet/install/lib:/home/hdail/local/omniORB-4.0.3-gcc3/lib:/home/hdail/local/gcc-3.0.4/lib"/>
        <end_point contact="192.5.59.201"/>
    </compute>
    <compute label="clus-107" disk="cristalDisk">
        <ssh server="192.5.59.202" login="hdail"/>
        <env path="/home/hdail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/hdail/bSeries_exp/diet/install/lib:/home/hdail/local/omniORB-4.0.3-gcc3/lib:/home/hdail/local/gcc-3.0.4/lib"/>
        <end_point contact="192.5.59.202"/>
    </compute>
    <compute label="clus-108" disk="cristalDisk">
        <ssh server="192.5.59.203" login="hdail"/>
        <env path="/home/hdail/bSeries_exp/bin/"
             LD_LIBRARY_PATH="/home/hdail/bSeries_exp/diet/install/lib:/home/hdail/local/omniORB-4.0.3-gcc3/lib:/home/hdail/local/gcc-3.0.4/lib"/>
        <end_point contact="192.5.59.203"/>
    </compute>

  </resources>
  
  <diet_services>
    <omni_names contact="193.253.175.224" port="2810">
	      <config server="ls2" remote_binary="omniNames"/>
    </omni_names>
    <log_central>
        <config server="ls2" remote_binary="LogCentral"/>
    </log_central>
    <test_tool>
        <config server="ls2" remote_binary="testTool"/>
    </test_tool>
  </diet_services>
  
  <diet_hierarchy>
    <master_agent>
	      <config server="clus-104" remote_binary="dietAgent"/>
   
	      <!-- diet components on LS --> 
        <local_agent>
	          <config server="ls1" remote_binary="dietAgent"/>
	          <local_agent>
		            <config server="ls6" remote_binary="dietAgent"/>
		            <SeD>
			            <config server="ls7" remote_binary="scalar_server"/>
		            </SeD>
            	  <SeD>
			            <config server="ls8" remote_binary="dmat_server"/>
			            <parameters string="MatPROD"/>
            	  </SeD>
            	  <SeD>
			            <config server="ls9" remote_binary="dmat_server"/>
			            <parameters string="MatSUM"/>
		            </SeD>
	          </local_agent>
            <SeD>
		            <config server="ls3" remote_binary="scalar_server"/>
            </SeD>
            <SeD>
		            <config server="ls4" remote_binary="scalar_server"/>
            </SeD>
            <SeD>
		            <config server="ls5" remote_binary="dmat_server"/>
		            <parameters string="T"/>
            </SeD>
        </local_agent>

	      <!-- DIET components on cristal -->
        <local_agent>
	          <config server="clus-105" remote_binary="dietAgent"/>
            
            <SeD>
		            <config server="clus-106" remote_binary="dmat_server"/>
                <parameters string="MatPROD"/>
            </SeD>
            <SeD>
	              <config server="clus-107" remote_binary="dmat_server"/>
                <parameters string="MatSUM"/>
            </SeD>
            <SeD>
	              <config server="clus-108" remote_binary="scalar_server"/>
            </SeD>
	      </local_agent>
    </master_agent>
  </diet_hierarchy>

</diet_configuration>

=== SysFera/GoDIET/examples/commented.xml
<?xml version="1.0" standalone="no"?>

<!DOCTYPE diet_configuration SYSTEM "../GoDIET.dtd">
<!-- GoDIET.dtd defines the semantics for input xml files for DIET.
     GoDIET uses a validating parser, so if your XML does not follow
     the rules specified in the dtd it will not be accepted by the
     parser. The comments below will help you write a valid XML for 
     GoDIET.  All sections are required unless marked "Optional" -->

<!-- The diet_configuration tags surround all of the other sections.
     diet_configuration can optionally contain:
       1 "goDiet" section: configure goDIET behavior
     and must contain each of the following:
       1 "resources" section: define storage and compute resources
       1 "diet_services" section: define omniNames, LogCentral, etc.
       1 "diet_hierarchy" section: define your agent hierarchy
-->
<diet_configuration>

  <!-- Optional: If desired, the goDiet section can be included to 
       allow configuration of goDIET behavior. -->
  <goDiet debug="1"
          saveStdOut="yes"
          saveStdErr="no"/>
        <!-- Optional: debug controls the verbosity of goDIET output from
                  0 (no debugging) -> 2 (very verbose) 
             Optional: saveStdOut controls whether stdout is redirected
                  to /dev/null or to a file in your remote scratch
                  space called <componentName>.out.
             Optional: saveStdErr as above with a file named 
                  <componentName>.err.
          -->
   
  <!-- Use the resources section to define what machines you
       want to use for computation and storage, how to access those
       resources, and where to find binaries on each. You must include
       1 "scratch" section, at least 1 "storage" section, and at least
       1 "compute" section. --> 
  <resources>
    <!-- Specify a local pathname GoDIET can use as scratch
         space (e.g. temp storage of config files). You must have write
         access to the directory. -->
    <scratch dir="/tmp/GoDIET_scratch"/>
  
    <!-- Define all storage space that will be needed to run 
         jobs on your compute hosts. -->
    <storage label="graalDisk">
        <scratch dir="/tmp/run_scratchGraal"/>
        <scp server="graal.ens-lyon.fr" login="hdail"/>
          <!-- Optional: if login is not specified, the current login
               is used. -->
    </storage>
    <storage label="localDisk">
        <scratch dir="/tmp/run_scratchLocal"/>
        <scp server="localhost"/>
    </storage>
    
    <!-- Define all compute hosts that you want to use.  The "disk" -->
    <compute label="graalHost" disk="graalDisk">
        <ssh server="graal.ens-lyon.fr" login="hdail"/>
          <!-- Optional: if login is not specified, the current login
               will be used. -->
        <env path="/home/hdail/local/LogCentral/bin:/home/hdail/local/LogCentral/examples:/home/hdail/local/src/diet/install/bin:/home/hdail/local/src/diet/src/examples/dmat_manips/"
             LD_LIBRARY_PATH="/usr/lib:/home/hdail/local/src/diet/install/lib"/>
             <!-- Optional: if you don't specify a path or
                  LD_LIBRARY_PATH, your default paths on the system will
                  be used. You can make the path shorter by putting
                  links to all your binaries in one directory on the
                  system. -->
    </compute>
    <compute label="localHost" disk="localDisk">
        <ssh server="localhost"/>
        <env path="/home/hdail/local/LogService/bin:/home/hdail/local/LogService/examples:/home/hdail/diet/omniORB-4.0.3/bin:/home/hdail/local/src/diet/install/bin:/home/hdail/local/src/diet/src/examples/dmat_manips/"
             LD_LIBRARY_PATH="/home/hdail/local/src/diet/install/lib:/home/hdail/diet/omniORB-4.0.3/lib"/>
    </compute>
  </resources>
 
  <!-- Define DIET services.  Must contain 1 "omni_names" section and
       can optionally include 1 "log_central" and 1 "test_tool"
       section.  Do not define "test_tool" without defining
       "log_central". -->
  <diet_services>

    <omni_names port="2810">
       <!-- Optional: if port is undefined, port 2809 will be used. -->
        <config server="localHost" 
                trace_level="1" 
                remote_binary="omniNames"/>
            <!-- "server" must refer to the label of one of your
                      "compute" resources defined above.  GoDIET will
                      run this service on that host.
                 "trace_level" is optional
                 "remote_binary" is the binary name to execute for the
                      service. -->
    </omni_names>

    <log_central>
        <config server="localHost" 
                trace_level="1" 
                remote_binary="LogCentral"/>
    </log_central>
    <test_tool>
        <config server="localHost" 
                trace_level="1" 
                remote_binary="testTool"/>
    </test_tool>
  </diet_services>
 
  <!-- Define desired DIET agent and server hierarchy.  Must include at
       least 1 "master_agent" section; all other sections are optional.
       -->
  <diet_hierarchy>

    <!-- Define config for "master_agent". -->
    <master_agent label="MyMA">
      <!-- "label" is optional.  If defined, it is used as a prefix for
           an automatically generated name.  The system will name this
           agent "MyMA_MA_0". -->
        <!-- See config explanation under "services" section -->
        <config server="localHost"
                trace_level="1"
                remote_binary="dietAgent"/>

        <!-- See "master_agent" explanation above. This agent will be 
             named MyLA_LA_0 -->
        <local_agent label="MyLA">
            <config server="localHost"
                    trace_level="1"
                    remote_binary="dietAgent"/>
            
            <SeD label="MySeD">
                <config server="localHost"
                        remote_binary="server"/>
                <parameters string="T"/>
            </SeD>
        </local_agent>
        <SeD label="MySeD">
            <config server="localHost"
                    remote_binary="server"/>
             <parameters string="T"/>
        </SeD>
    </master_agent>
  </diet_hierarchy>      

</diet_configuration>
