=== SysFera/GoDIET/src/main/resources/GoDiet.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name='diet_configuration'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='goDiet' minOccurs='0' maxOccurs='1' />
				<xs:element ref='resources' />
				<xs:element ref='diet_services' />
				<xs:element ref='diet_hierarchy' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name='goDiet'>
		<xs:complexType>
			<xs:attribute name='debug' type='xs:string' use='optional' />
			<xs:attribute name='saveStdOut' type='xs:string' use='optional' />
			<xs:attribute name='saveStdErr' type='xs:string' use='optional' />
			<xs:attribute name='useUniqueDirs' type='xs:string' use='optional' />
			<xs:attribute name='log' type='xs:string' use='optional' />
			<xs:attribute name='watcherPeriod' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='resources'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='scratch' />
				<xs:element ref='storage' maxOccurs='unbounded' />
				<xs:element ref='compute' minOccurs='0' maxOccurs='unbounded' />
				<xs:element ref='cluster' minOccurs='0' maxOccurs='unbounded' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name='storage'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='scratch' />
				<xs:element ref='scp' />
			</xs:sequence>
			<xs:attribute name='label' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='scratch'>
		<xs:complexType>
			<xs:attribute name='dir' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='scp'>
		<xs:complexType>
			<xs:attribute name='login' type='xs:string' use='optional' />
			<xs:attribute name='server' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='compute'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='ssh' />
				<xs:element ref='env' minOccurs='0' maxOccurs='1' />
				<xs:element ref='end_point' minOccurs='0' maxOccurs='1' />
			</xs:sequence>
			<xs:attribute name='disk' type='xs:string' use='required' />
			<xs:attribute name='label' type='xs:string' use='required' />
			<xs:attribute name='login' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='cluster'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='env' />
				<xs:element ref='node' maxOccurs='unbounded' />
			</xs:sequence>
			<xs:attribute name='disk' type='xs:string' use='required' />
			<xs:attribute name='label' type='xs:string' use='required' />
			<xs:attribute name='login' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='node'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='ssh' />
				<xs:element ref='end_point' minOccurs='0' maxOccurs='1' />
			</xs:sequence>
			<xs:attribute name='label' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='ssh'>
		<xs:complexType>
			<xs:attribute name='server' type='xs:string' use='required' />
			<xs:attribute name='login' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='env'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='var' minOccurs='0' maxOccurs='unbounded' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name='end_point'>
		<xs:complexType>
			<xs:attribute name='contact' type='xs:string' use='optional' />
			<xs:attribute name='startPort' type='xs:string' use='optional' />
			<xs:attribute name='endPort' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='var'>
		<xs:complexType>
			<xs:attribute name='name' type='xs:string' use='required' />
			<xs:attribute name='value' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='diet_services'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='omni_names' />
				<xs:element ref='log_central' minOccurs='0' maxOccurs='1' />
				<xs:element ref='log_tool' minOccurs='0' maxOccurs='1' />
				<xs:element ref='diet_statistics' minOccurs='0'
					maxOccurs='1' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name='omni_names'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='config' />
				<xs:element ref='cfg_options' minOccurs='0' maxOccurs='1' />
			</xs:sequence>
			<xs:attribute name='contact' type='xs:string' use='required' />
			<xs:attribute name='port' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='log_central'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='config' />
			</xs:sequence>
			<xs:attribute name='connectDuringLaunch' type='xs:string'
				use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='log_tool'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='config' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name='diet_statistics'>
		<xs:complexType />
	</xs:element>

	<xs:element name='diet_hierarchy'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='master_agent' maxOccurs='unbounded' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name='agent'>
		<xs:sequence>
			<xs:element ref='config' />
			<xs:element ref='cfg_options' minOccurs='0' maxOccurs='1' />
			<xs:element ref='local_agent' minOccurs='0' maxOccurs='unbounded' />
			<xs:element ref='SeD' minOccurs='0' maxOccurs='unbounded' />
		</xs:sequence>
		<xs:attribute name='label' type='xs:string' use='optional' />
		<xs:attribute name='useDietStats' type='xs:string' use='optional' />
	</xs:complexType>
	<xs:element name='master_agent'>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base='agent'>
					<xs:sequence>
						<xs:element ref='ma_dag' minOccurs='0' maxOccurs='unbounded' />
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>


		</xs:complexType>

	</xs:element>

	<xs:element name='ma_dag'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='config' />
				<xs:element ref='cfg_options' minOccurs='0' maxOccurs='1' />
				<xs:element ref='parameters' minOccurs='0' maxOccurs='1' />
			</xs:sequence>
			<xs:attribute name='label' type='xs:string' use='optional' />
			<xs:attribute name='useDietStats' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='local_agent'>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base='agent' />
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:element name='SeD'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='config' />
				<xs:element ref='cfg_options' minOccurs='0' maxOccurs='1' />
				<xs:element ref='parameters' minOccurs='0' maxOccurs='1' />
			</xs:sequence>
			<xs:attribute name='label' type='xs:string' use='optional' />
			<xs:attribute name='useDietStats' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='config'>
		<xs:complexType>
			<xs:attribute name='remote_binary' type='xs:string' use='required' />
			<xs:attribute name='server' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='parameters'>
		<xs:complexType>
			<xs:attribute name='string' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='cfg_options'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='option' maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name='option'>
		<xs:complexType>
			<xs:attribute name='name' type='xs:string' use="required" />
			<xs:attribute name='value' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>

</xs:schema>

=== SysFera/GoDIET/src/main/resources/examples/examplePhi.xml
<?xml version="1.0" encoding="UTF-8"?>
<diet_configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="GoDiet.xsd">

    <goDiet debug="1"
            saveStdOut="yes"
            saveStdErr="yes"
            useUniqueDirs="no"/>

    <resources>
        <scratch dir="/home/phi/tmp/scratch_godiet"/>

        <storage label="localDisk">
            <scratch dir="/home/phi/tmp/scratch_runtime"/>
            <scp server="localhost"/>
        </storage>

        <compute label="localHost" disk="localDisk">
            <ssh server="localhost"/>
	    <env>
		    <var name="PATH" value="/home/phi/Soft/Diet/bin:/home/phi/Soft/Diet/bin/examples/dmat_manips/:$PATH"/>
		    <var name="LD_LIBRARY_PATH" value="/home/phi/Soft/Diet/lib"/>
	    </env>
        </compute>
    </resources>
  
    <diet_services>
        <omni_names contact="192.168.1.16" port="2809">
            <config server="localHost" remote_binary="omniNames"/>
        </omni_names>
    </diet_services>
  
    <diet_hierarchy>
        <master_agent>
            <config server="localHost" remote_binary="dietAgent"/>
    
            <local_agent>
                <config server="localHost" remote_binary="dietAgent"/>
            
                <SeD>
                    <config server="localHost" remote_binary="dmat_manips_server"/>
                    <parameters string="T"/>
                </SeD>
            </local_agent>
        </master_agent>
    </diet_hierarchy>      

</diet_configuration>

=== SysFera/GoDIET/src/main/resources/examples/exampleKevin.xml
<?xml version="1.0" encoding="UTF-8"?>
<diet_configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="GoDiet.xsd">

	<goDiet debug="1" saveStdOut="yes" saveStdErr="yes"
		useUniqueDirs="no" />

	<resources>
		<scratch dir="/home/phi/tmp/scratch_godiet" />


		<storage label="kevinDisk">
			<scratch dir="/tmp/scratch_runtime" />
			<scp server="192.168.1.20" />
		</storage>

		<storage label="graalDisk">
			<scratch dir="/tmp/scratch_runtime" />
			<scp server="140.77.166.19" login="pmartinez" />
		</storage>

		<storage label="phiDisk">
			<scratch dir="/home/phi/tmp/scratch_runtime" />
			<scp server="192.168.1.16" />
		</storage>

		<compute label="Kev" disk="kevinDisk">
			<ssh server="kevin" />
			<env>
				<var name="PATH"
					value="/home/phi/Diet/build/bin:/home/phi/Diet/build/bin/examples/dmat_manips/:$PATH" />
				<var name="LD_LIBRARY_PATH" value="/home/phi/Diet/build/lib" />
			</env>
		</compute>
		<compute label="Phi" disk="phiDisk">
			<ssh server="localhost" />
			<env>
				<var name="PATH"
					value="/home/phi/Soft/Diet/bin:/home/phi/Soft/Diet/bin/examples/dmat_manips/:$PATH" />
				<var name="LD_LIBRARY_PATH" value="/home/phi/Soft/Diet/lib" />
			</env>
		</compute>


		<compute label="Graal" disk="graalDisk">
			<ssh server="graal" login="pmartinez" />
			<env>
				<var name="PATH"
					value="/home/pmartinez/Diet/build/bin:/home/pmartinez/Diet/build/bin/examples/dmat_manips/:$PATH" />
				<var name="LD_LIBRARY_PATH" value="/home/pmartinez/Diet/build/lib" />
			</env>
		</compute>

	</resources>
	<!--<diet_services>
		<omni_names contact="192.168.1.16" port="2809">
			<config server="localHost" remote_binary="omniNames" />
		</omni_names>
	</diet_services>
	--><diet_hierarchy>
		<master_agent>
			<config server="Phi" remote_binary="dietAgent" />

			<local_agent>
				<config server="Phi" remote_binary="dietAgent" />

				<SeD>
					<config server="Graal" remote_binary="dmat_manips_server" />
					<parameters string="T" />
				</SeD>
			</local_agent>
		</master_agent>
	</diet_hierarchy>

</diet_configuration>

=== SysFera/GoDIET/src/test/resources/exampleMultiDomains.xml
<?xml version="1.0" encoding="UTF-8"?>
<diet_configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="GoDiet.xsd">

	<goDiet debug="1" saveStdOut="true" saveStdErr="true" log="true">
		<scratch dir="/home/phi/tmp/scratch_godiet" />
	</goDiet>

	<infrastructure>
		<domain label="Sysfera">
			<storage label="kevinDisk">
				<scratch dir="/tmp/scratch_runtime" />
				<scp server="192.168.1.17" login="phi" />
			</storage>
			<storage label="phiDisk">
				<scratch dir="/home/phi/tmp/scratch_runtime" />
				<scp server="192.168.1.20" login="phi" />
			</storage>

			<compute id="Kev" disk="kevinDisk">
				<ssh server="192.168.1.17" login="phi" />
				<env>
					<var name="PATH"
						value="/home/phi/Diet/build/bin:/home/phi/Diet/build/bin/examples/dmat_manips/:$PATH" />
					<var name="LD_LIBRARY_PATH" value="/home/phi/Diet/build/lib" />
				</env>
			</compute>
			<compute id="Phi" disk="phiDisk">
				<ssh server="192.168.1.20" login="phi" />
				<env>
					<var name="PATH"
						value="/home/phi/Soft/Diet/bin:/home/phi/Soft/Diet/bin/examples/dmat_manips/:$PATH" />
					<var name="LD_LIBRARY_PATH" value="/home/phi/Soft/diet/build/lib" />
				</env>
			</compute>
			<gateway id="SysferaGW" ref="Kev" />
		</domain>
		<domain label="ENS">
			<storage label="graalDisk">
				<scratch dir="/tmp/scratch_runtime" />
				<scp server="140.77.166.19" login="pmartinez" />
			</storage>


			<compute id="Graal" disk="graalDisk">
				<ssh server="140.77.166.19" login="pmartinez" />
				<env>
					<var name="PATH"
						value="/home/pmartinez/Diet/build/bin:/home/pmartinez/Diet/build/bin/examples/dmat_manips/:$PATH" />
					<var name="LD_LIBRARY_PATH"
						value="/home/pmartinez/Diet/build/lib:/home/bdepardo/soft/omniORB/lib" />
				</env>
			</compute>
			<gateway id="ENSGW" ref="Graal" />

		</domain>

		<link from="SysferaGW" to="ENSGW" />
	</infrastructure>

	<diet_services>
		<omni_names contact="192.168.1.17" port="2809" domain="Sysfera">
			<config server="Kev" remote_binary="omniNames" />
		</omni_names>
		<omni_names contact="140.77.166.19" port="2809" domain="ENS">
			<config remote_binary="omniNames" server="Graal" />
		</omni_names>
	</diet_services>

	<diet_hierarchy>
		<master_agent>
			<config server="Kev" remote_binary="dietAgent" />
			<local_agent>
				<config server="Graal" remote_binary="dietAgent" />
				<SeD>
					<config server="Graal" remote_binary="dmat_manips_server" />
					<parameters string="T" />
				</SeD>
			</local_agent>
		</master_agent>
	</diet_hierarchy>

</diet_configuration>
