=== SysFera/GoDIET/src/test/resources/GoDietNG.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" jaxb:version="2.0">

	<xs:element name="diet_configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="goDiet" type="goDiet" minOccurs="0"
					maxOccurs="1" />
				<xs:element name="infrastructure" type="infrastructure" />
				<xs:element name="diet_services" type="diet_services" />
				<xs:element name="diet_hierarchy" type="diet_hierarchy" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="goDiet">
		<xs:sequence>
			<xs:element name="scratch" type="scratch" />
		</xs:sequence>
		<xs:attribute name="debug" type="xs:int" default="1" />
		<xs:attribute name="saveStdOut" type="xs:boolean"
			default="true" />
		<xs:attribute name="saveStdErr" type="xs:boolean"
			default="true" />
		<xs:attribute name="log" type="xs:boolean" />
		<xs:attribute name="watcherPeriod" type="xs:int" default="30000" />
	</xs:complexType>


	<xs:complexType name="infrastructure">
		<xs:sequence>
			<xs:element name="domain" type="domain" maxOccurs="unbounded" />
			<xs:element name="link" type="link" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="link">
		<xs:attribute name="from" type="xs:IDREF" use="required">
			<xs:annotation>
				<xs:appinfo>
					<jaxb:property>
						<jaxb:baseType name="Gateway" />
					</jaxb:property>
				</xs:appinfo>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="to" type="xs:IDREF" use="required">
			<xs:annotation>
				<xs:appinfo>
					<jaxb:property>
						<jaxb:baseType name="Gateway" />
					</jaxb:property>
				</xs:appinfo>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>


	<xs:complexType name="domain">
		<xs:sequence>
			<xs:element name="storage" type="storage" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="node" type="node" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="cluster" type="cluster" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="gateway" type="gateway" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="label" />
	</xs:complexType>

	<xs:complexType name="resource" abstract="true">
		<xs:attribute name="id" type="xs:ID" use="required" />
	</xs:complexType>


	<xs:complexType name="gateway">
		<xs:complexContent>
			<xs:extension base="resource">
				<xs:attribute name="ref" type="xs:IDREF" use="required">
					<xs:annotation>
						<xs:appinfo>
							<jaxb:property>
								<jaxb:baseType name="Node" />
							</jaxb:property>
						</xs:appinfo>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>

	</xs:complexType>



	<xs:complexType name="frontend">
		<xs:complexContent>
			<xs:extension base="gateway"></xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="storage">

		<xs:sequence>
			<xs:element name="scratch" type="scratch" />
			<xs:element name="scp" type="scp" />
		</xs:sequence>
		<xs:attribute name="label" type="xs:ID" use="required" />
	</xs:complexType>

	<xs:complexType name="scratch">
		<xs:attribute name="dir" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="scp">
		<xs:attribute name="login" type="xs:string" use="required" />
		<xs:attribute name="server" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="node">
		<xs:complexContent>
			<xs:extension base="resource">
				<xs:sequence>
					<xs:element name="ssh" type="ssh" />
					<xs:element name="env" type="env" minOccurs="0"
						maxOccurs="1" />
					<xs:element name="end_point" type="end_point" minOccurs="0"
						maxOccurs="1" />
				</xs:sequence>
				<xs:attribute name="disk" type="xs:IDREF" use="required">
					<xs:annotation>
						<xs:appinfo>
							<jaxb:property>
								<jaxb:baseType name="Storage" />
							</jaxb:property>
						</xs:appinfo>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="login" type="xs:string" use="optional" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="cluster">
		<xs:sequence>
			<xs:element name="computingnode" type="node" maxOccurs="unbounded" />
			<xs:element name="frontend" type="frontend" />
		</xs:sequence>
		<xs:attribute name="cardinality" type="xs:int" use="required" />
		<xs:attribute name="label" type="xs:string" use="required" />
		<xs:attribute name="login" type="xs:string" use="optional" />
	</xs:complexType>



	<xs:complexType name="ssh">
		<xs:attribute name="server" type="xs:string" use="required" />
		<xs:attribute name="login" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="env">
		<xs:sequence>
			<xs:element name="var" type="var" minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="end_point">
		<xs:attribute name="contact" type="xs:string" use="optional" />
		<xs:attribute name="startPort" type="xs:string" use="optional" />
		<xs:attribute name="endPort" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="var">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>


	<xs:complexType name="diet_services">
		<xs:sequence>
			<xs:element name="omni_names" type="omni_names" minOccurs="1"
				maxOccurs="unbounded" />
			<xs:element name="log_central" type="log_central"
				minOccurs="0" maxOccurs="1" />
			<xs:element name="log_tool" type="log_tool" minOccurs="0"
				maxOccurs="1" />

		</xs:sequence>
		<xs:attribute name="statistics" type="xs:boolean"
			default="false"></xs:attribute>
	</xs:complexType>

	<xs:complexType name="omni_names">
		<xs:sequence>
			<xs:element name="config" type="config" />
			<xs:element name="cfg_options" type="cfg_options"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="contact" type="xs:string" use="required" />
		<xs:attribute name="port" type="portType" use="optional"
			default="2809" />
		<xs:attribute name="domain" />
	</xs:complexType>


	<xs:complexType name="log_central">
		<xs:sequence>
			<xs:element name="config" type="config" />
		</xs:sequence>
		<xs:attribute name="connectDuringLaunch" type="xs:string"
			use="optional" />
	</xs:complexType>

	<xs:complexType name="log_tool">
		<xs:sequence>
			<xs:element name="config" type="config" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="diet_hierarchy">
		<xs:sequence>
			<xs:element name="master_agent" type="master_agent"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="agent" abstract="true">
		<xs:sequence>
			<xs:element name="config" type="config" />
			<xs:element name="cfg_options" type="cfg_options"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="label" type="xs:string" use="optional" />
		<xs:attribute name="stats" type="xs:boolean" default="false" />
	</xs:complexType>


	<xs:complexType name="master_agent">
		<xs:complexContent>
			<xs:extension base="agent">
				<xs:sequence>
					<xs:element name="ma_dag" type="ma_dag" minOccurs="0"
						maxOccurs="unbounded" />
					<xs:element name="local_agent" type="local_agent"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="sed" type="sed" minOccurs="0"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ma_dag">
		<xs:complexContent>
			<xs:extension base="agent">
				<xs:sequence>
					<xs:element name="parameters" type="parameters"
						maxOccurs="1" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="local_agent">
		<xs:complexContent>
			<xs:extension base="agent">
				<xs:sequence>

					<xs:element name="local_agent" type="local_agent"
						minOccurs="0" maxOccurs="unbounded" />
					<xs:element name="sed" type="sed" minOccurs="0"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="sed">
		<xs:complexContent>
			<xs:extension base="agent">
				<xs:sequence>
					<xs:element name="parameters" type="parameters"
						maxOccurs="unbounded" minOccurs="0" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="config">
		<xs:attribute name="remote_binary" type="xs:string" use="required" />
		<xs:attribute name="server" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="parameters">
		<xs:attribute name="string" type="xs:string" use="required" />
	</xs:complexType>


	<xs:complexType name="cfg_options">
		<xs:sequence>
			<xs:element name="option" type="option" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="option">
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="required" />
	</xs:complexType>

	<xs:simpleType name="portType">
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0" />
			<xs:maxInclusive value="65535" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== SysFera/GoDIET/src/main/resources/examples/exampleMultiDomains.xml
<?xml version="1.0" encoding="UTF-8"?>
<diet_configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="GoDietNG.xsd">

	<goDiet debug="1" saveStdOut="yes" saveStdErr="yes"
		useUniqueDirs="no" />

	<resources>
		<scratch dir="/home/phi/tmp/scratch_godiet" />

		<storage label="kevinDisk">
			<scratch dir="/tmp/scratch_runtime" />
			<scp server="192.168.1.17" />
		</storage>

		<storage label="graalDisk">
			<scratch dir="/tmp/scratch_runtime" />
			<scp server="140.77.166.19" login="pmartinez" />
		</storage>

		<storage label="phiDisk">
			<scratch dir="/home/phi/tmp/scratch_runtime" />
			<scp server="192.168.1.20" />
		</storage>

		<infrastructure>
			<domain label="Sysfera">
			<gateway label="SysferaGW" address="127.0.0.1" port="22" login="phi"/>
				<compute label="Kev" disk="kevinDisk">
					<ssh server="kevin" />
					<env>
						<var name="PATH"
							value="/home/phi/Diet/build/bin:/home/phi/Diet/build/bin/examples/dmat_manips/:$PATH" />
						<var name="LD_LIBRARY_PATH" value="/home/phi/Diet/build/lib" />
					</env>
				</compute>
				<compute label="Phi" disk="phiDisk">
					<ssh server="192.168.1.20" />
					<env>
						<var name="PATH"
							value="/home/phi/Soft/Diet/bin:/home/phi/Soft/Diet/bin/examples/dmat_manips/:$PATH" />
						<var name="LD_LIBRARY_PATH" value="/home/phi/Soft/diet/build/lib" />
					</env>
				</compute>
			</domain>
			<domain label="ENS">
				<gateway label="ENSGW" address="140.77.166.19" port="22" login="pmartinez"/>
				<compute label="Graal" disk="graalDisk">
					<ssh server="graal" login="pmartinez" />
					<env>
						<var name="PATH"
							value="/home/pmartinez/Diet/build/bin:/home/pmartinez/Diet/build/bin/examples/dmat_manips/:$PATH" />
						<var name="LD_LIBRARY_PATH" value="/home/pmartinez/Diet/build/lib:/home/bdepardo/soft/omniORB/lib" />
					</env>
				</compute>
			</domain>
			
			<link from="SysferaGW" to="ENSGW"/>
		</infrastructure>
	</resources>

	<diet_services>
		<omni_names contact="192.168.1.20" port="2809" domain="Sysfera">
			<config server="Phi" remote_binary="omniNames" />
		</omni_names>
		<omni_names contact="140.77.166.19" port="2809" domain="ENS">
			<config remote_binary="omniNames" server="Graal" />
		</omni_names>
	</diet_services>

	<diet_hierarchy>
		<master_agent>
			<config server="Phi" remote_binary="dietAgent" /><!-- <local_agent> 
				<config server="Graal" remote_binary="dietAgent" /> <SeD> <config server="Graal" 
				remote_binary="dmat_manips_server" /> <parameters string="T" /> </SeD> </local_agent> -->
		</master_agent>
	</diet_hierarchy>

</diet_configuration>

=== SysFera/GoDIET/src/test/resources/exampleMultiDomainsNG.xml
<?xml version="1.0" encoding="UTF-8"?>
<diet_configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="GoDietNG.xsd">

	<goDiet debug="1" saveStdOut="true" saveStdErr="true"
		log="true">
		<scratch dir="/home/phi/tmp/scratch_godiet" />
	</goDiet>

		<infrastructure>
			<domain label="Sysfera">
				<storage label="kevinDisk">
					<scratch dir="/tmp/scratch_runtime" />
					<scp server="192.168.1.17" login="phi" />
				</storage>
				<storage label="phiDisk">
					<scratch dir="/home/phi/tmp/scratch_runtime" />
					<scp server="192.168.1.20" login="phi" />
				</storage>

				<node id="Kev" disk="kevinDisk">
					<ssh server="192.168.1.17" login="phi" />
					<env>
						<var name="PATH"
							value="/home/phi/Diet/build/bin:/home/phi/Diet/build/bin/examples/dmat_manips/:$PATH" />
						<var name="LD_LIBRARY_PATH" value="/home/phi/Diet/build/lib" />
					</env>
				</node>
				<node id="Phi" disk="phiDisk">
					<ssh server="192.168.1.20" login="phi" />
					<env>
						<var name="PATH"
							value="/home/phi/Soft/Diet/bin:/home/phi/Soft/Diet/bin/examples/dmat_manips/:$PATH" />
						<var name="LD_LIBRARY_PATH" value="/home/phi/Soft/diet/build/lib" />
					</env>
				</node>
				<gateway id="SysferaGW" ref="Kev" />
			</domain>
			<domain label="ENS">
				<storage label="graalDisk">
					<scratch dir="/tmp/scratch_runtime" />
					<scp server="140.77.166.19" login="pmartinez" />
				</storage>


				<node id="Graal" disk="graalDisk">
					<ssh server="140.77.166.19" login="pmartinez" />
					<env>
						<var name="PATH"
							value="/home/pmartinez/Diet/build/bin:/home/pmartinez/Diet/build/bin/examples/dmat_manips/:$PATH" />
						<var name="LD_LIBRARY_PATH"
							value="/home/pmartinez/Diet/build/lib:/home/bdepardo/soft/omniORB/lib" />
					</env>
				</node>
				<gateway id="ENSGW" ref="Graal" />

			</domain>

			<link from="SysferaGW" to="ENSGW" />
		</infrastructure>

	<diet_services>
		<omni_names contact="192.168.1.17" port="2809" domain="Sysfera">
			<config server="Kev" remote_binary="omniNames" />
		</omni_names>
		<omni_names contact="140.77.166.19" port="2809" domain="ENS">
			<config remote_binary="omniNames" server="Graal" />
		</omni_names>
	</diet_services>

	<diet_hierarchy>
		<master_agent>
			<config server="Kev" remote_binary="dietAgent" />
			<local_agent>
				<config server="Graal" remote_binary="dietAgent" />
				<sed>
					<config server="Graal" remote_binary="dmat_manips_server" />
					<parameters string="T" />
				</sed>
			</local_agent>
		</master_agent>
	</diet_hierarchy>

</diet_configuration>
